# Generated by Django 2.1.1 on 2018-09-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subway_line', models.CharField(max_length=30)),
                ('station', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('workingtime', models.CharField(max_length=30)),
                ('likes', models.IntegerField()),
                ('explanation', models.CharField(max_length=200)),
                ('images', models.ImageField(default='media/image.png', upload_to='')),
            ],
        ),
    ]
