# Generated by Django 2.1.1 on 2018-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reviews',
            field=models.IntegerField(default=324),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='views',
            field=models.IntegerField(default=32049),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
